Description: 
    Creates an EC2 with HTTP access on port 8888

Parameters:
    GithubBranch:
        Type: String
        Default: dev

    AvailabilityZone:
        Description: AWS Availability Zone
        Type: AWS::EC2::AvailabilityZone::Name
        Default: us-east-1a

    InstanceType:
        Description: EC2 instance type
        Type: String
        Default: t2.micro

    SSHKey:
        Description: SSH Key Name
        Type: String
        Default: scott-ouellette-extension-school

    AMI:
        Description: AMI to create the EC2
        Type: String
        Default: ami-058f0b6d904c90419

Resources:
    SecurityGroup:
        Type: 'AWS::EC2::SecurityGroup'
        Properties:
            GroupName: !Sub SSH_HTTP_ACCESS-${GithubBranch}
            GroupDescription: Internet access port 8888
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: '8888'
                  ToPort: '8888'
                  CidrIp: 0.0.0.0/0
                - IpProtocol: tcp
                  FromPort: '22'
                  ToPort: '22'
                  CidrIp: 0.0.0.0/0
    # EC2 Instances -------------------------------------
    
    JenkinsEC2:
        Type: 'AWS::EC2::Instance'
        Properties:
          ImageId: !Ref AMI
          InstanceType: !Ref InstanceType
          KeyName: !Ref SSHKey
          Tags:
            - 
              Key: Name
              Value: !Sub JenkinsEC2-${GithubBranch}
          SecurityGroupIds:
            - !Ref SecurityGroup
          UserData:
            Fn::Base64:
              Fn::Sub:
                - |
                  #!/bin/bash -xe
                  yum install -y git docker

                  systemctl enable docker
                  systemctl start docker

                  mkdir -p /root/.ssh

                  cat > /root/.ssh/id_rsa << EOF
                  -----BEGIN RSA PRIVATE KEY-----
                  MIIEpAIBAAKCAQEAnI8JU+eC/BHuW+Ye6CQZ6Xcf/7jz3+9dt6WKNRvzjo1p2y1n
                  d3/vRHZ0PLMomq3+iZYnWjeEpvMHwolivSuIuG+J/ogx96JiLr557C2UtyziZjZQ
                  ZEHm8queQYUIRPDF3q39K7wrKqncfBDvXR4ho3nw6Ep41cVCq1Czr9TUxzcG4dTa
                  kz2xjYYGve9EyEaGGDvVlBI2XBxXrrrzESmXK+WykKjLZ8Lsdaud53NiAv5ZAHFd
                  sa8T0s4si5iaGnm8nid3hRot2eoPFX1sAgYd3FPbGybS4mqY0RQdaqjUZuDRCwds
                  WGQLU/IzoW/p7gOzqyf7ucTfNRRGBS766H8/hwIDAQABAoIBAHRxTpbBUoL5MzfW
                  6JXwg/VJTNt+TKT5+9JjpW/q4jPcqicCljojRWq+T6X1+vVRBEiBDbPkJx2lFNh0
                  JqRchMvo6dIOqltsw2nQ8g3fuQSktZ8gNprbCVLkokhJEeV0zzbYYbztr42D2SHN
                  1rqDdrGIOM4M1eLpXLTeyUa2Haws7z7EEjQsscOT+DP2zqLRlRlIvx1yJcCqITdu
                  ehf2jd82n6JujMcpdefraWxjIb3tnfAb6zOg2c1tJaWxwrFgGvUvoU9hL3rf42A3
                  nHIYnnZLu/vjYEce1qtLUhAJKMiNB53cTYr3X0i2lodHk7yupcoyLnfNrdYlUHrl
                  Hdp4f8ECgYEA0F4a5Xu1ICXeNn8ftzb0ACVSkvTXii7Oy4ZXWteT4KWXkZkIuwZ7
                  Dknhz2BzmGaH+NgUtDQ0hyficiaM1efBYJq2EGsBHkp7hEDC9eEBIzkQipEi73ZK
                  lxsEk0sn0LMrkeBA2S6DZacEBUW2B0NvZkqw+Rg5lUS1CDGJr9Mk1G0CgYEAwFkF
                  dDq0x29wthyzDYnCKJ4X5TBtiVTXDdnn5KjBFZNDrEjvRGg498BOUPx+DcEv7/0I
                  yCnuRgG67pre7xRUC7x3H+7Z1WO9NFIWMtpy7jT1/obozv1ggxDC9ZS1yBK3Y37J
                  NDZqEVxQYAggF9XieuAGHICKSvgg2xbiCy4b40MCgYB0Pqverv9DahzoZk95VU0W
                  77t7hODilG6GGPKPGYnEYF2IusmmHV11gT5bBUI4Gatt5o7WYfGUHWo1qNAVXfAC
                  Rw2fZzL+hSsXg1HA/sA1uFZEF+hXk7TVTBtnWRxjUDHUdjl3cH2Zrm2Ny3Bb6QEz
                  HiRRM3Sck/IzGf/oeXEomQKBgQCWyHJVFfxHZx3VNRRL5ZT14FDdEqSbho17RznY
                  701Fi4b+VMJ0PruBxBfgtr5eK/ZXTGWI/A3UhWCz0WY3xxjHhntf5g6PkDtu+3Z5
                  cPOttoisebehI9F3jTk36NbDu6BVd7tkmc92QoajcVsvNDTxnBJOX5mJgY/ID90t
                  ZHzqHwKBgQCNH0HL7gh68FpduKt1HFdMKl26VRYdAgP5+N8wjbSayqllw+e5ZfM0
                  e6uTvZtPtELDWAFXAQtdU1lRYn+5/tTT1mdBGPWKRWnV1zeSItZGf0zpQUj2jrCM
                  lZarLkhSaQqck93yaXA3DxQOpPZYBK0UweW41gv+PgqFMRJGruW6fA==
                  -----END RSA PRIVATE KEY-----
                  EOF

                  chmod 700 /root/.ssh
                  chmod 600 /root/.ssh/id_rsa
                  ssh-keyscan github.com 2>&1  | grep rsa >> /root/.ssh/known_hosts

                  mkdir -p /root/final-project-pub
                  /bin/git clone git@github.com:rfarchoukh/final-project-pub.git /root/final-project-pub
                  cd /root/final-project-pub
                  /bin/git checkout ${GITHUB_BRANCH}
                  /bin/git pull

                  /bin/bash /root/final-project-pub/dockerScript.sh
                - GITHUB_BRANCH: !Ref GithubBranch
